export const deptGroupFormat = [
	{
		id: 'igu',
		number:'1',
		name: 'IIT Roorkee IGU Student Chapter',
		tagline:'Student Chapter',
		content:'IGU Student Chapter, IIT Roorkee is a non-profit organisation, which aim towards making coveted efforts to pursue and disseminate Geo-scientific knowledge and activities among the fellow students at the Department of Earth sciences IIT Roorkee.',
		contactPerson: 'Vishvendra Singh',
		contactNumber: '7455840360',
		socialMedia:{
			facebook: 'https://www.facebook.com/iguiitr/',
			linkedIn:'',
			instagram: '',
			twitter: '',
			personal: '',
			github: '',
		},
		image: '/images/igu.jpg',
		projects :[],
		equipments : [],
		recruitments:'Pre-requisites: - Student of GT/GPT only, modest communication and presentation skills. Recruitment: - 1st Round:  Online Google Form having to submit general information of interest and personal details. 2nd Round:  Interview. 3rd Round:  Presentation on different associations of earth sciences across the world. '
	},
	{
		id: 'sae',
		number:'2',
		name: 'SAE Chapter IIT Roorkee',
		tagline:'Society of Automotive Engineers-Chapter IIT Roorkee',
		content:  'SAE IIT Roorkee is a group of enthusiastic and self-motivated undergraduate engineers who thrive to pursue their interest in automobiles. The mission is to create a pool of inquisitive and innovative minds by means of sharing knowledge and fuelling passion.It is a collegiate chapter of SAE INDIA, which is affiliated to SAE International.',
		contactPerson: 'Debjit Tripathy',
		contactNumber: '9437284363',
		socialMedia:{
			facebook: 'https://www.facebook.com/SAEIITR/',
			linkedIn:'',
			instagram: '',
			twitter: '',
			personal: '',
			github: '',
		},
		image: '/images/sae.jpg',
		projects :[ [{
			projectName : 'RC Cars',
			projectContent: 'Students work on a scaled down model of an IC engine car that is remote controlled. The manufacturing and tuning of the components provides a thorough learning of how an IC engine driven vehicle works.The team then participates in Powerdrift, the centrestage event at Cognizance-the annual technical fest of IIT Roorkee.',
		},
		{
			projectName : 'SAE Aero',
			projectContent: 'A relatively new initiative by SAE IIT Roorkee, it caters to the needs of all aeromodelling enthusiasts on campus. Tinkering with UAVs and participating in national level competitions, the group is already brimming with innovative individuals working together, with a will to fly higher.',
		}]
		],
		equipments : [],
		recruitments:'SAE IIT Roorkee runs a lecture series for freshers in their first semester itself. These serve the purpose of getting students acquainted with the technical knowledge about automobiles. The recruitment process begins in the Spring semester with a written test revolving around basic knowhow of automobiles and reasoning. The study material is also made available on SAE IITR\'s blog. ',	
	},
	{
		id: 'acm',
		number:'3',
		name: 'ACM IIT Roorkee Chapter',
		tagline:'Association of Computer Machinery',
		content:  'It is an official student body incepted in 2014 under the aegis of Department of Computer Science and Engineering, IIT Roorkee. It organizes a number of events including programming contests, talks by renowned speakers, workshops etc. which gives the students an exposure to the competitive computing world as well as allows them to understand the advancements going on in the computing sphere worldwide.',
		contactPerson: 'Akash Gupta',
		contactNumber: '8226050690',
		socialMedia:{
			facebook: 'https://www.facebook.com/groups/acmiitrteam/',
			linkedIn:'',
			instagram: '',
			twitter: '',
			personal: '',
			github: '',
		},
		image: '/images/acm.jpg',
		projects :[],
		equipments : [],
		recruitments:'ACM IITR Chapter is open as of now.',	
	},
	{
		id: 'cec',
		number:'4',
		name: 'CEC IITR',
		tagline:'Civil Engineering Consortium',
		content:  'Civil Engineering Consortium is the departmental group of Civil Engineering Department, IIT Roorkee. The group was established to act as a bridge between the students ( of both, Btech and Mtech programmes) and the faculty.We at CEC carry out activities all the year round to provide the stage for the budding talent amongst the civilians and also help provide them aid in their academic journey here at IITR and beyond.',
		contactPerson: 'Pracheer Mehra',
		contactNumber: '7500320832',
		socialMedia:{
			facebook: 'https://www.facebook.com/ceconsortium.iitr/',
			linkedIn:'',
			instagram: '',
			twitter: '',
			personal: '',
			github: '',
		},
		image: '/images/cec.jpg',
		projects :[],
		equipments : ['Modem(1)','Black board(1)'],
		recruitments:'A written test to sort the requisites into various verticals.(May involve submission of past works based on questionnaire).And then followed by formal interviews. ',	
	},
	{
		id: 'mech',
		number:'5',
		name: 'MIESS',
		tagline:'Mechanical and Industrial Engineering Student\'s Society',
		content:  'The official student body of the Mechanical and Industrial Engineering Department IIT Roorkee. The primary objectives of MIESS for the next session will be to act as a helping platform to increase the participation of students in Technical events and competitions. Increasing Inter-college collaboration to enable the students to get the much-wanted exposure. Establish an identity outside of being the official group representing our department.',
		contactPerson: 'Samarth Gubrele',
		contactNumber: '8349146260',
		socialMedia:{
			facebook: 'https://www.facebook.com/MIESS.IITR/?hc_ref=ARTJuAiTse4hRKOeuQpQNVz40bJEGzdcFOqFqXK0CDrLR8Ux_uOid5W-spMry2mAc5o&fref=nf',
			linkedIn:'',
			instagram: '',
			twitter: '',
			personal: '',
			github: '',
		},
		image: '/images/miess.jpg',
		projects :[],
		equipments : [],
		recruitments:'The recruitment process consists of two steps: 1)Written test/Submission for designers and developers 2)Personal Interviews',	
	},

];

