export const achievements = [
	 'ArIES were world finalist in Valeo Innovation Challenge 2017 (International Competition aimed at rewarding an innovative project)',
	 'ArIES secured the gold as well as silver Medal in Inter IIT TechMeet 2018.',
	 'ArIES were featured winner in Global NIPS 2017 Paper Implementation Challenge.',
	 'ArIES secured 2nd place in Pitney Bowes SMB International Hackathon.',
	 'ArIES were Finalist in Niyantra 2017 (annual design contest organised by National Instruments).',
	 'ArIES were the National Winners in Digimize’17.',
	 'ArIES secured 3rd place in code.fun.do in 2018 and in Microsoft Garage AI Hackathon2017.',
	 'Aries secured 3rd place in WiFi Thinkfest 2.0 (A competition to design new applications and services aimed at serving Rural India).',
	 'Team IRC  ASME IIT chapter won 2nd place in the national level and 3rd place in the international level in the International Robotics challenge.',
	 'Student Lead design Conference(SLDC)2016-1st and 2nd position in Technical Web Page presentation, 3rd position in Video Presentation.',
	 'ASME Asia pacific E-fest 2017-Won first prize in Old guard Oral presentation,represented India at final level held at Florida.',
	 'ASME won 11th and 12th postion in design and inovation respectively in HPVC(human powered vehicle Challenge) 2016.',
	 'ASME won 2nd in “Robosapiens” in Cognizance 2016 , 2nd in “poseidon” Cognizance 2017, 3rd in “Cyborg break in” Cognizance in 2018.',
	 'Design Studio grabbed the first runner-up position in mascot design during Inter-IIT Cultural Meet 2017.',
	 'The team of Enactus IIT Roorkee stood out as one of the top 12 teams of the total 160 participating teams  at the National level Finals.',
	 'Enactus was selected amongst top 3 teams out of 160 to represent IIT Roorkee chapter in UN’s Young Changemakers Conclave 2018.',
	 'MaRS Team came 4th in “Technology for Soldier Support” a problem statement by DRDO among 11 IITs in Inter IIT tech meet 2018.',
	 'MaRS acquired 5th position in “Automatic Toilet Cleaner” among 11 IITs in Inter IIT tech meet 2018.',
	 '“Mino - The Reaction Bot” made by MaRS bagged 1st position among all the IIT’s in the Inter IIT Tech meet 2017.”',
	 'MaRS grabbed 5th rank in the category ‘Indoor Localisation’, in Inter IIT Tech meet 2017.',
	 'MaRS in collaboration with ArIES bagged 5th rank in the category ‘UAV Design Challenge’ in Inter IIT Tech meet 2017.',
	 'MDG got selcted for the grand finale of Smart India Hackathon 2017.',
	 'MDG won the 1st and 3rd positions in Cognizance Appathon 2017.',
	 'MDG was the winner of Panasonic Mobivation Award.',
	 'MDG was 1st and 2nd Runner up in Microsoft Code.fun.Do onsite 2017.',
	 'MDG Secured 4th place and won a cash prize of INR 10K in 108 Hackathon organised by TNHSP and IIT Madras.',
	 'Team Robocon were awarded with the Best Debut Team Award - ABU Robocon Nationals 2009.',
	 'Team Robocon: 7/115 Best Innovative Design Award Winner - ABU Robocon Nationals 2018.',
	 'Team Robocon: 5/108 Best Aesthetic Design Award Winner - ABU Robocon Nationals 2016.',
	 'Team Robocon: 5/105 Best Aesthetic Design Award Winner - ABU Robocon Nationals 2014.',
	 'SDS was Yahoo HackU IITD winners in 2011 and Adobe express app winners in 2012.',
	 'SDS was Deloitte CCSC winners in 2013, 2014, 2015.',
	 'SDS was Microsoft Code.fun.do winner in the years 2014, 2015, 2017, 2018.',
	 'SDS was Imagine cup India finalist, Angel Hacks runner ups and ntel India embedded challenge winners in 2014.',
	 'SDS was Topcoder open hackathon winner and Quikr API hackathon winner in 2015.',
	 'SDS was Microsoft Build the Shield winner, India Hacks Game development winner and CSAW CTF winner in 2016.',
	 'SDS were the Inter IIT Hackathon gold medalist in 2018.',
	 'Raja Jain and Nimisha Gupta of ShARE won the Finals of Schneider Electric Challenge - Go Green in the City.',
	 'Ankit Bagaria of ShARE along with 2 fellow students won the Ericsson Innovation Award 2017.',
	 'Rishabh Jha led the 5-member team comprising 2 students from IIT Roorkee to win the I-batch competition organized by ShARE Global in 2017.',
	 'Agrim Patodia of ShARE and 2 other IIT Roorkee students won the Gold Medal in Inter IIT Technical Meet, Kanpur.',
	 'Ghanendra Shrivastava alongside 2 other ShARE IITR members were the Finalists in the GE Edison Challenge 2016.',
	 'Uday Shinghal alongside 4 other members from ShARE IITR went into the Finals of the Indian Case Challenge 2017 organized in IIT Kharagpur.',
	 'Nimisha Gupta and 4 other ShARE IITR members won the case challenge organized by Shell in Cognizance, IIT Roorkee.',
	 'Ankit Bagaria, Uday Shinghal along with 2 fellow members won the Gold Medal in the Case Study Competition, Inter IIT Tehchnical Meet - Madras.',
	 'Team KNOx secured 2nd place among 326 teams in CAE category (awarded by ANSYS) in 2013',
	 'Team KNOx secured overall rank 10 among 280 teams in 2011 in CAE category.',
	 'Team KNOx secured overall 13 rank among 288 teams and no.1 among IITs in 2012 in CAE category.',
	 'Runner up at Inter IIT Tech Meet 2k19'
	];